### ISSUE TITLE
TypeError: proxy.$i18n.messages is undefined

### ISSUE THREAD

**Issue by dreamFinoa** [XM-GO/PandaUi#5]
Chrome显示的问题
![11](https://user-images.githubusercontent.com/8405870/192790933-3bdd90e7-cc6a-4db6-be2b-1265deebb8ea.png)
firefox显示的问题
![22](https://user-images.githubusercontent.com/8405870/192791040-3f481741-6e2e-4abd-b58d-d910c8bef815.png)
错误位置代码
![33](https://user-images.githubusercontent.com/8405870/192791097-d5d7875e-4a78-4167-8b41-d28f35b431f2.png)

**Comment by XM-GO** [comment]
已修复
